on:
  repository_dispatch:
    types: docker-process
name: preload-image
jobs:
  deploy:
    name: cleaning previous file and pre loading the image(s) at the edge
    runs-on: ubuntu-latest
    steps:
    - name: process data received
      id: event-received
      shell: bash
      run: |
        echo IMAGE NAME ${{ github.event.client_payload.image_name }}
        echo TAG ${{ github.event.client_payload.tag }}
        echo repo_key ${{ github.event.client_payload.repo_key }}
        echo path ${{ github.event.client_payload.path }}
        echo name ${{ github.event.client_payload.name }}