on:
  repository_dispatch:
    types: docker-process
name: preload-image
jobs:
  deploy:
    name: Pre loading at the edge
    runs-on: ubuntu-latest
    steps:
    - name: Setup JFrog CLI
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
    - name: process data received
      id: event-received
      shell: bash
      run: |
        echo IMAGE NAME ${{ github.event.client_payload.image_name }}
        echo TAG ${{ github.event.client_payload.tag }}
        echo repo_key ${{ github.event.client_payload.repo_key }}
        echo path ${{ github.event.client_payload.path }}
        echo name ${{ github.event.client_payload.name }}
        echo "clearing the edge cache"
        jf rt del ${{ vars.JF_TARGET_REPO }}-cache/${{ github.event.client_payload.path }}
        echo "pulling image to preload it in the cache"
        jf docker pull ${{ vars.JF_HOST }}/${{ vars.JF_TARGET_REPO }}/${{ github.event.client_payload.image_name }}:${{ github.event.client_payload.tag}}
